-- CoreStream App: demo persistente SIN autenticación real.
-- Ejecutar una vez después de ficha_avance_02.sql. Es idempotente y no borra
-- tickets existentes. IMPORTANTE: las políticas anon son abiertas sólo para
-- una demostración pública con datos ficticios; nunca usar con datos reales.

create table if not exists public.demo_users (
  id text primary key,
  full_name text not null,
  role text not null check (role in ('ADMIN','GROUP_LEADER','DEVELOPER')),
  specialty text,
  avatar_color_hex text not null default '#4C8DFF',
  is_active boolean not null default true,
  is_login_option boolean not null default false
);

alter table public.tickets
  add column if not exists spent_seconds integer not null default 0,
  add column if not exists blocked_seconds integer not null default 0,
  add column if not exists running_since timestamptz,
  add column if not exists blocked_since timestamptz,
  add column if not exists pr_link text,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by_id text;

create table if not exists public.ticket_subtasks (
  id text primary key default gen_random_uuid()::text,
  ticket_id text not null references public.tickets(id),
  title text not null,
  done boolean not null default false,
  order_index integer not null default 0
);

create table if not exists public.ticket_events (
  id bigint generated always as identity primary key,
  ticket_id text not null references public.tickets(id),
  type text not null,
  user_id text not null,
  to_user_id text,
  text text,
  from_status text,
  to_status text,
  created_at timestamptz not null default now()
);

create table if not exists public.demo_incidents (
  id text primary key default gen_random_uuid()::text,
  number bigint generated by default as identity unique,
  application_id text not null references public.applications(id),
  title text not null,
  description text not null default '',
  category text not null,
  severity text not null,
  status text not null default 'OPEN',
  reporter_id text not null,
  assignee_id text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.demo_incident_comments (
  id bigint generated always as identity primary key,
  incident_id text not null references public.demo_incidents(id),
  user_id text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.demo_notifications (
  id text primary key default gen_random_uuid()::text,
  user_id text not null references public.demo_users(id),
  kind text not null,
  message text not null,
  ticket_id text,
  incident_id text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_demo_tickets_epic on public.tickets(epic_id) where deleted_at is null;
create index if not exists idx_demo_subtasks_ticket on public.ticket_subtasks(ticket_id);
create index if not exists idx_demo_events_ticket on public.ticket_events(ticket_id, created_at);
create index if not exists idx_demo_notifs_user on public.demo_notifications(user_id, created_at desc);

alter table public.demo_users enable row level security;
alter table public.ticket_subtasks enable row level security;
alter table public.ticket_events enable row level security;
alter table public.demo_incidents enable row level security;
alter table public.demo_incident_comments enable row level security;
alter table public.demo_notifications enable row level security;

-- Se conserva la tabla de tickets previa; se amplía el CRUD de la demo.
drop policy if exists demo_tickets_update on public.tickets;
create policy demo_tickets_update on public.tickets for update to anon, authenticated
  using (true) with check (true);
drop policy if exists demo_tickets_read on public.tickets;
-- La política anterior ficha_read_tickets sigue habilitando SELECT.

drop policy if exists demo_users_read on public.demo_users;
create policy demo_users_read on public.demo_users for select to anon, authenticated using (true);

drop policy if exists demo_subtasks_read on public.ticket_subtasks;
create policy demo_subtasks_read on public.ticket_subtasks for select to anon, authenticated using (true);
drop policy if exists demo_subtasks_update on public.ticket_subtasks;
create policy demo_subtasks_update on public.ticket_subtasks for update to anon, authenticated
  using (true) with check (true);

drop policy if exists demo_events_read on public.ticket_events;
create policy demo_events_read on public.ticket_events for select to anon, authenticated using (true);
drop policy if exists demo_events_insert on public.ticket_events;
create policy demo_events_insert on public.ticket_events for insert to anon, authenticated with check (true);

drop policy if exists demo_incidents_read on public.demo_incidents;
create policy demo_incidents_read on public.demo_incidents for select to anon, authenticated using (true);
drop policy if exists demo_incidents_update on public.demo_incidents;
create policy demo_incidents_update on public.demo_incidents for update to anon, authenticated
  using (true) with check (true);

drop policy if exists demo_incident_comments_read on public.demo_incident_comments;
create policy demo_incident_comments_read on public.demo_incident_comments for select to anon, authenticated using (true);

drop policy if exists demo_notifs_read on public.demo_notifications;
create policy demo_notifs_read on public.demo_notifications for select to anon, authenticated using (true);
drop policy if exists demo_notifs_insert on public.demo_notifications;
create policy demo_notifs_insert on public.demo_notifications for insert to anon, authenticated with check (true);
drop policy if exists demo_notifs_update on public.demo_notifications;
create policy demo_notifs_update on public.demo_notifications for update to anon, authenticated
  using (true) with check (true);

grant select on public.demo_users, public.ticket_subtasks, public.ticket_events,
  public.demo_incidents, public.demo_incident_comments, public.demo_notifications
  to anon, authenticated;
grant update on public.tickets, public.ticket_subtasks, public.demo_incidents,
  public.demo_notifications to anon, authenticated;
grant insert on public.ticket_events, public.demo_notifications to anon, authenticated;

insert into public.demo_users (id, full_name, role, specialty, avatar_color_hex, is_login_option) values
  ('u1','Ana Torres','ADMIN','Arquitectura de soluciones','#4C8DFF',true),
  ('u2','Luis Vega','GROUP_LEADER','Backend · Líder equipo Pagos','#8B7CF6',true),
  ('u3','Diego Ramos','DEVELOPER','Frontend · Vue / TypeScript','#2FBF71',true),
  ('u4','Sofía Márquez','DEVELOPER','Full-stack · Integraciones','#F2A93B',false),
  ('u5','Marco Ibáñez','DEVELOPER','QA · Automatización','#F0554E',false)
on conflict (id) do nothing;

insert into public.applications (id,name,code,color_hex) values
  ('a1','Portal Clientes','PC','#4C8DFF'),
  ('a2','API Pagos','AP','#2FBF71'),
  ('a3','App Logística','AL','#8B7CF6')
on conflict (id) do nothing;

insert into public.epics (id,application_id,name,order_index) values
  ('e1','a1','Autenticación y seguridad',0),
  ('e2','a1','Panel de autogestión',1),
  ('e3','a2','Conciliación bancaria',0),
  ('e4','a2','Webhooks de pago',1),
  ('e5','a3','Seguimiento de flotas',0)
on conflict (id) do nothing;

insert into public.tickets
  (id,number,epic_id,title,description,status,priority,assignee_id,created_by_id,
   due_date,spent_seconds,blocked_seconds,running_since,pr_link)
values
  ('t4',139,'e2','Editar datos fiscales con validación de NIF/CIF',
   'Formulario de datos fiscales con validación en tiempo real y verificación contra el censo.',
   'DONE','LOW','u5','u2',now()-interval '1 day',24300,0,null,'https://github.com/wellq/portal/pull/412'),
  ('t5',145,'e3','Matching automático de transferencias SEPA',
   'Cruce de transferencias entrantes con facturas pendientes.',
   'IN_PROGRESS','URGENT','u4','u2',now()-interval '1 day',33120,3300,now()-interval '5 minutes',null),
  ('t6',143,'e3','Alertas de descuadre superior a 50 €',
   'Notificar al equipo de finanzas cuando el descuadre diario supere el umbral.',
   'TODO','HIGH','u3','u1',now()+interval '4 days',0,0,null,null),
  ('t7',137,'e4','Reintentos exponenciales en webhooks fallidos',
   'Hasta 6 reintentos con backoff exponencial y firma HMAC en cada entrega.',
   'REDIRECTED','HIGH','u3','u2',now()+interval '3 days',5400,0,null,null),
  ('t8',146,'e5','Mapa en vivo con posiciones GPS cada 30 s',
   'Websocket con posiciones de la flota y clustering de marcadores.',
   'IN_PROGRESS','MEDIUM','u5','u1',now()+interval '9 days',11100,0,now()-interval '5 minutes',null),
  ('t9',134,'e5','Firma digital de albaranes en la entrega',
   'Captura de firma táctil y foto del paquete como prueba de entrega.',
   'TODO','LOW',null,'u1',now()+interval '14 days',0,0,null,null)
on conflict (id) do nothing;

-- Completar atributos no presentes en la primera ficha, sin sobrescribir
-- cambios posteriores hechos por usuarios de la demo.
update public.tickets set spent_seconds=15720, blocked_seconds=2100,
  running_since=now()-interval '12 minutes', due_date=now()+interval '2 days'
where id='t1' and spent_seconds=0 and status='IN_PROGRESS';
update public.tickets set spent_seconds=7800, blocked_seconds=10800,
  blocked_since=now()-interval '5 hours', due_date=now()+interval '1 day'
where id='t2' and spent_seconds=0 and status='BLOCKED';
update public.tickets set due_date=now()+interval '6 days'
where id='t3' and due_date is null;

insert into public.ticket_subtasks (id,ticket_id,title,done,order_index) values
  ('s1','t1','Pantalla de enrolamiento TOTP',true,0),
  ('s2','t1','Validación de código de 6 dígitos',true,1),
  ('s3','t1','Códigos de respaldo descargables',false,2),
  ('s4','t1','Tests E2E del flujo completo',false,3),
  ('s5','t2','Contador de intentos en Redis',true,0),
  ('s6','t2','Plantilla de correo de aviso',false,1),
  ('s7','t3','Endpoint GET /invoices/:id/pdf',false,0),
  ('s8','t3','Listado con paginación',false,1),
  ('s9','t4','Validador NIF/CIF',true,0),
  ('s10','t4','Mensajes de error accesibles',true,1),
  ('s11','t5','Parser de extractos CAMT.053',true,0),
  ('s12','t5','Motor de matching por referencia',true,1),
  ('s13','t5','Cola de revisión manual',false,2),
  ('s14','t5','Informe diario de no conciliados',false,3),
  ('s15','t6','Umbral configurable por app',false,0),
  ('s16','t7','Scheduler de reintentos',true,0),
  ('s17','t7','Panel de entregas fallidas',false,1),
  ('s18','t8','Canal WS /fleet/positions',true,0),
  ('s19','t8','Clustering de marcadores',false,1),
  ('s20','t8','Modo ahorro de datos',false,2)
on conflict (id) do nothing;

insert into public.demo_incidents
  (id,number,application_id,title,description,category,severity,status,reporter_id,assignee_id,created_at)
values
  ('i1',57,'a2','Timeout al conciliar extractos de más de 5 000 líneas',
   'El worker corta el proceso al superar 30 s.','CRITICAL_ERROR','CRITICAL','IN_PROGRESS','u2','u4',now()-interval '26 hours'),
  ('i2',58,'a1','El selector de idioma no persiste tras cerrar sesión',
   'Al volver a entrar, el portal vuelve a español.','NON_CRITICAL_ERROR','LOW','OPEN','u3',null,now()-interval '8 hours'),
  ('i3',55,'a1','Añadir exportación de movimientos a Excel',
   'Exportar el histórico de movimientos a XLSX.','NEW_FEATURE','MEDIUM','UNDER_REVIEW','u1','u3',now()-interval '3 days'),
  ('i4',52,'a3','Contraste insuficiente en el mapa nocturno',
   'Los marcadores grises apenas se distinguen.','USABILITY_ISSUE','MEDIUM','RESOLVED','u5','u5',now()-interval '6 days'),
  ('i5',60,'a2','Webhook duplicado cuando el receptor responde 5xx lento',
   'Si el receptor tarda más de 10 s y devuelve 502, se duplica.','CRITICAL_ERROR','HIGH','OPEN','u4',null,now()-interval '3 hours')
on conflict (id) do nothing;

-- Historial inicial de los tickets de ejemplo. Los eventos nuevos se agregan
-- desde la app y permanecen incluso después del archivado lógico.
insert into public.ticket_events
  (ticket_id,type,user_id,to_user_id,text,from_status,to_status,created_at)
select seed.ticket_id,seed.type,seed.user_id,seed.to_user_id,
       seed.text,seed.from_status,seed.to_status,seed.created_at
from (values
  ('t1','CREATED','u2',null::text,null::text,null::text,null::text,now()-interval '4 days'),
  ('t1','ASSIGNED','u2','u3',null,null,null,now()-interval '4 days'+interval '1 minute'),
  ('t1','STATUS','u3',null,null,'TODO','IN_PROGRESS',now()-interval '3 days'),
  ('t1','COMMENT','u2',null,'Prioriza la compatibilidad con 1Password.',null,null,now()-interval '1 day'),
  ('t2','CREATED','u2',null,null,null,null,now()-interval '6 days'),
  ('t2','ASSIGNED','u2','u4',null,null,null,now()-interval '6 days'+interval '1 minute'),
  ('t2','QUESTION','u4',null,'¿El bloqueo aplica también a los accesos por API?',null,null,now()-interval '5 hours'),
  ('t3','CREATED','u1',null,null,null,null,now()-interval '2 days'),
  ('t4','CREATED','u2',null,null,null,null,now()-interval '9 days'),
  ('t4','COMPLETED','u5',null,null,null,null,now()-interval '1 day'),
  ('t5','CREATED','u2',null,null,null,null,now()-interval '8 days'),
  ('t6','CREATED','u1',null,null,null,null,now()-interval '3 days'),
  ('t7','CREATED','u2',null,null,null,null,now()-interval '7 days'),
  ('t7','REDIRECTED','u5','u3','Diego conoce el panel de entregas.',null,null,now()-interval '2 days'),
  ('t8','CREATED','u1',null,null,null,null,now()-interval '5 days'),
  ('t9','CREATED','u1',null,null,null,null,now()-interval '1 day')
) as seed(ticket_id,type,user_id,to_user_id,text,from_status,to_status,created_at)
where exists (select 1 from public.tickets t where t.id=seed.ticket_id)
  and not exists (
    select 1 from public.ticket_events e
    where e.ticket_id=seed.ticket_id and e.type=seed.type
      and e.user_id=seed.user_id
      and e.text is not distinct from seed.text
  );

insert into public.demo_incident_comments (incident_id,user_id,text,created_at)
select 'i1','u4','Reproducido con un extracto de 8 200 líneas; el cuello está en el parser.',
       now()-interval '20 hours'
where not exists (select 1 from public.demo_incident_comments where incident_id='i1');

insert into public.demo_notifications
  (id,user_id,kind,message,ticket_id,incident_id,is_read,created_at)
values
  ('n1','u3','ASSIGNMENT','Ana Torres te asignó: “Alertas de descuadre superior a 50 €”','t6',null,true,now()-interval '3 days'),
  ('n2','u1','QUESTION','Sofía Márquez preguntó por “Bloqueo de cuenta tras 5 intentos fallidos”','t2',null,false,now()-interval '5 hours'),
  ('n3','u2','QUESTION','Sofía Márquez preguntó por “Bloqueo de cuenta tras 5 intentos fallidos”','t2',null,false,now()-interval '5 hours'),
  ('n4','u1','INCIDENT','Sofía Márquez reportó una incidencia en API Pagos',null,'i5',false,now()-interval '3 hours'),
  ('n5','u2','INCIDENT','Sofía Márquez reportó una incidencia en API Pagos',null,'i5',false,now()-interval '3 hours')
on conflict (id) do nothing;

-- Evita que un ticket nuevo reciba T-1 pese a los números precargados.
select setval(pg_get_serial_sequence('public.tickets','number'),
  greatest((select coalesce(max(number),1) from public.tickets),1), true);
select setval(pg_get_serial_sequence('public.demo_incidents','number'),
  greatest((select coalesce(max(number),1) from public.demo_incidents),1), true);
