-- CoreStream App · Ficha Avance 02 (DuocUC)
-- Ejecutar una vez en Supabase > SQL Editor.

create table if not exists public.applications (
  id text primary key,
  name text not null,
  code text not null unique,
  color_hex text not null default '#4C8DFF'
    check (color_hex ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.epics (
  id text primary key,
  application_id text not null references public.applications(id) on delete cascade,
  name text not null,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id text primary key default gen_random_uuid()::text,
  number bigint generated by default as identity unique,
  epic_id text not null references public.epics(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 5 and 120),
  description text not null default '',
  status text not null default 'TODO'
    check (status in ('TODO', 'IN_PROGRESS', 'BLOCKED', 'REDIRECTED', 'DONE')),
  priority text not null default 'MEDIUM'
    check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
  assignee_id text,
  created_by_id text,
  due_date timestamptz,
  created_at timestamptz not null default now()
);

alter table public.applications enable row level security;
alter table public.epics enable row level security;
alter table public.tickets enable row level security;

drop policy if exists "ficha_read_applications" on public.applications;
create policy "ficha_read_applications"
  on public.applications for select to anon, authenticated using (true);

drop policy if exists "ficha_read_epics" on public.epics;
create policy "ficha_read_epics"
  on public.epics for select to anon, authenticated using (true);

drop policy if exists "ficha_read_tickets" on public.tickets;
create policy "ficha_read_tickets"
  on public.tickets for select to anon, authenticated using (true);

drop policy if exists "ficha_create_tickets" on public.tickets;
create policy "ficha_create_tickets"
  on public.tickets for insert to anon, authenticated
  with check (
    status = 'TODO'
    and priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')
    and char_length(trim(title)) between 5 and 120
  );

grant usage on schema public to anon, authenticated;
grant select on public.applications, public.epics, public.tickets to anon, authenticated;
grant insert on public.tickets to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.applications (id, name, code, color_hex)
values ('a1', 'Portal Clientes', 'PC', '#4C8DFF')
on conflict (id) do update set
  name = excluded.name,
  code = excluded.code,
  color_hex = excluded.color_hex;

insert into public.epics (id, application_id, name, order_index)
values
  ('e1', 'a1', 'Autenticación y seguridad', 0),
  ('e2', 'a1', 'Panel de autogestión', 1)
on conflict (id) do update set
  application_id = excluded.application_id,
  name = excluded.name,
  order_index = excluded.order_index;

insert into public.tickets
  (id, number, epic_id, title, description, status, priority, assignee_id, created_by_id)
values
  ('t1', 132, 'e1', 'Implementar login con doble factor (TOTP)',
   'Añadir verificación TOTP tras la contraseña.', 'IN_PROGRESS', 'HIGH', 'u3', 'u2'),
  ('t2', 128, 'e1', 'Bloqueo de cuenta tras 5 intentos fallidos',
   'Aplicar bloqueo temporal y aviso al usuario.', 'BLOCKED', 'MEDIUM', 'u4', 'u2'),
  ('t3', 141, 'e2', 'Descarga de facturas en PDF desde el panel',
   'Permitir descargar facturas en formato PDF.', 'TODO', 'MEDIUM', null, 'u1')
on conflict (id) do update set
  epic_id = excluded.epic_id,
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  priority = excluded.priority,
  assignee_id = excluded.assignee_id,
  created_by_id = excluded.created_by_id;

-- Consulta útil como evidencia antes y después de crear el ticket D:
-- select number, title, status, priority, epic_id, created_at
-- from public.tickets order by created_at, number;
